name: Deploy Web App With Pgbench Prefix Branch
env:
  DEPLOY_PKG_DIR: deploy_pkg
  DEPLOY_ZIP: deploy.zip
  WAIT_SECONDS: "20"
  STARTUP_FILE: "gunicorn --bind=0.0.0.0 --timeout 600 app.main:app"

on:
  workflow_dispatch:
    inputs:
      webapp_name:
        description: "Azure Web App name"
        required: false
        type: string
      resource_group:
        description: "Azure Resource Group for the target web app"
        required: false
        type: string
  push:
    branches:
      - pgbench/* # Check out flexible-federated-credential setup to enable this workflow for all branches with /pgbench prefix, or change to your desired branch pattern.
  pull_request:
    branches:
      - pgbench/* # Check out flexible-federated-credential setup to enable this workflow for all branches with /pgbench prefix, or change to your desired branch pattern.

jobs:
  reuse-workflow:
    uses: ./.github/workflows/build-flask-wapp.yml
    secrets: inherit
  