name: Publish GH App Test Image

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SHA_IMAGE_TAG: brkndocker/ghapp-test:${{ github.sha }}
  DOCKER_TEST_IMAGE: brkndocker/ghapp-test:latest

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push image
        run: bash scripts/push-ghapp-image.sh
        