name: GitHub App Docker Flow Test (Local Dockerfile)

env:
  TARGET_REPO: BarkinKctp/ghapp-oidc-deploy-test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APPLICATION_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app.outputs.token }}
          
      - name: Install python requirements
        run:  python -m pip install -r requirements.txt

      - name: Run main tests
        id: main_tests
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
        run: python -m unittest app.tests.main_test

      - name: Build image and run tests in Docker
        id: docker_tests
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          PLATFORM: debian
          IMAGE_NAME: flask-app-test
        run: python -m app.build_packages

      - name: Write and push test result file
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
          TARGET_BRANCH: main
          MAIN_TEST_OUTCOME: ${{ steps.main_tests.outcome }}
          DOCKER_TEST_OUTCOME: ${{ steps.docker_tests.outcome }}
        run: bash scripts/push-results.sh
          